package com.hua.shi.rmd.domain.entity.finance;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FinanceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public FinanceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeIsNull() {
            addCriterion("finance_code is null");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeIsNotNull() {
            addCriterion("finance_code is not null");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeEqualTo(String value) {
            addCriterion("finance_code =", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeNotEqualTo(String value) {
            addCriterion("finance_code <>", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeGreaterThan(String value) {
            addCriterion("finance_code >", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("finance_code >=", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeLessThan(String value) {
            addCriterion("finance_code <", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeLessThanOrEqualTo(String value) {
            addCriterion("finance_code <=", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeLike(String value) {
            addCriterion("finance_code like", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeNotLike(String value) {
            addCriterion("finance_code not like", value, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeIn(List<String> values) {
            addCriterion("finance_code in", values, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeNotIn(List<String> values) {
            addCriterion("finance_code not in", values, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeBetween(String value1, String value2) {
            addCriterion("finance_code between", value1, value2, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceCodeNotBetween(String value1, String value2) {
            addCriterion("finance_code not between", value1, value2, "financeCode");
            return (Criteria) this;
        }

        public Criteria andFinanceNameIsNull() {
            addCriterion("finance_name is null");
            return (Criteria) this;
        }

        public Criteria andFinanceNameIsNotNull() {
            addCriterion("finance_name is not null");
            return (Criteria) this;
        }

        public Criteria andFinanceNameEqualTo(String value) {
            addCriterion("finance_name =", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameNotEqualTo(String value) {
            addCriterion("finance_name <>", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameGreaterThan(String value) {
            addCriterion("finance_name >", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameGreaterThanOrEqualTo(String value) {
            addCriterion("finance_name >=", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameLessThan(String value) {
            addCriterion("finance_name <", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameLessThanOrEqualTo(String value) {
            addCriterion("finance_name <=", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameLike(String value) {
            addCriterion("finance_name like", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameNotLike(String value) {
            addCriterion("finance_name not like", value, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameIn(List<String> values) {
            addCriterion("finance_name in", values, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameNotIn(List<String> values) {
            addCriterion("finance_name not in", values, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameBetween(String value1, String value2) {
            addCriterion("finance_name between", value1, value2, "financeName");
            return (Criteria) this;
        }

        public Criteria andFinanceNameNotBetween(String value1, String value2) {
            addCriterion("finance_name not between", value1, value2, "financeName");
            return (Criteria) this;
        }

        public Criteria andBidCodeIsNull() {
            addCriterion("bid_code is null");
            return (Criteria) this;
        }

        public Criteria andBidCodeIsNotNull() {
            addCriterion("bid_code is not null");
            return (Criteria) this;
        }

        public Criteria andBidCodeEqualTo(String value) {
            addCriterion("bid_code =", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeNotEqualTo(String value) {
            addCriterion("bid_code <>", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeGreaterThan(String value) {
            addCriterion("bid_code >", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bid_code >=", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeLessThan(String value) {
            addCriterion("bid_code <", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeLessThanOrEqualTo(String value) {
            addCriterion("bid_code <=", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeLike(String value) {
            addCriterion("bid_code like", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeNotLike(String value) {
            addCriterion("bid_code not like", value, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeIn(List<String> values) {
            addCriterion("bid_code in", values, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeNotIn(List<String> values) {
            addCriterion("bid_code not in", values, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeBetween(String value1, String value2) {
            addCriterion("bid_code between", value1, value2, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidCodeNotBetween(String value1, String value2) {
            addCriterion("bid_code not between", value1, value2, "bidCode");
            return (Criteria) this;
        }

        public Criteria andBidNameIsNull() {
            addCriterion("bid_name is null");
            return (Criteria) this;
        }

        public Criteria andBidNameIsNotNull() {
            addCriterion("bid_name is not null");
            return (Criteria) this;
        }

        public Criteria andBidNameEqualTo(String value) {
            addCriterion("bid_name =", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameNotEqualTo(String value) {
            addCriterion("bid_name <>", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameGreaterThan(String value) {
            addCriterion("bid_name >", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameGreaterThanOrEqualTo(String value) {
            addCriterion("bid_name >=", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameLessThan(String value) {
            addCriterion("bid_name <", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameLessThanOrEqualTo(String value) {
            addCriterion("bid_name <=", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameLike(String value) {
            addCriterion("bid_name like", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameNotLike(String value) {
            addCriterion("bid_name not like", value, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameIn(List<String> values) {
            addCriterion("bid_name in", values, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameNotIn(List<String> values) {
            addCriterion("bid_name not in", values, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameBetween(String value1, String value2) {
            addCriterion("bid_name between", value1, value2, "bidName");
            return (Criteria) this;
        }

        public Criteria andBidNameNotBetween(String value1, String value2) {
            addCriterion("bid_name not between", value1, value2, "bidName");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyIsNull() {
            addCriterion("start_purchase_money is null");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyIsNotNull() {
            addCriterion("start_purchase_money is not null");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyEqualTo(BigDecimal value) {
            addCriterion("start_purchase_money =", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyNotEqualTo(BigDecimal value) {
            addCriterion("start_purchase_money <>", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyGreaterThan(BigDecimal value) {
            addCriterion("start_purchase_money >", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("start_purchase_money >=", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyLessThan(BigDecimal value) {
            addCriterion("start_purchase_money <", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("start_purchase_money <=", value, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyIn(List<BigDecimal> values) {
            addCriterion("start_purchase_money in", values, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyNotIn(List<BigDecimal> values) {
            addCriterion("start_purchase_money not in", values, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_purchase_money between", value1, value2, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andStartPurchaseMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_purchase_money not between", value1, value2, "startPurchaseMoney");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxIsNull() {
            addCriterion("expect_yield_max is null");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxIsNotNull() {
            addCriterion("expect_yield_max is not null");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxEqualTo(BigDecimal value) {
            addCriterion("expect_yield_max =", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxNotEqualTo(BigDecimal value) {
            addCriterion("expect_yield_max <>", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxGreaterThan(BigDecimal value) {
            addCriterion("expect_yield_max >", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("expect_yield_max >=", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxLessThan(BigDecimal value) {
            addCriterion("expect_yield_max <", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("expect_yield_max <=", value, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxIn(List<BigDecimal> values) {
            addCriterion("expect_yield_max in", values, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxNotIn(List<BigDecimal> values) {
            addCriterion("expect_yield_max not in", values, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expect_yield_max between", value1, value2, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andExpectYieldMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("expect_yield_max not between", value1, value2, "expectYieldMax");
            return (Criteria) this;
        }

        public Criteria andRealYieldIsNull() {
            addCriterion("real_yield is null");
            return (Criteria) this;
        }

        public Criteria andRealYieldIsNotNull() {
            addCriterion("real_yield is not null");
            return (Criteria) this;
        }

        public Criteria andRealYieldEqualTo(BigDecimal value) {
            addCriterion("real_yield =", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldNotEqualTo(BigDecimal value) {
            addCriterion("real_yield <>", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldGreaterThan(BigDecimal value) {
            addCriterion("real_yield >", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_yield >=", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldLessThan(BigDecimal value) {
            addCriterion("real_yield <", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_yield <=", value, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldIn(List<BigDecimal> values) {
            addCriterion("real_yield in", values, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldNotIn(List<BigDecimal> values) {
            addCriterion("real_yield not in", values, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_yield between", value1, value2, "realYield");
            return (Criteria) this;
        }

        public Criteria andRealYieldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_yield not between", value1, value2, "realYield");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNull() {
            addCriterion("value_date is null");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNotNull() {
            addCriterion("value_date is not null");
            return (Criteria) this;
        }

        public Criteria andValueDateEqualTo(Date value) {
            addCriterion("value_date =", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotEqualTo(Date value) {
            addCriterion("value_date <>", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThan(Date value) {
            addCriterion("value_date >", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("value_date >=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThan(Date value) {
            addCriterion("value_date <", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThanOrEqualTo(Date value) {
            addCriterion("value_date <=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIn(List<Date> values) {
            addCriterion("value_date in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotIn(List<Date> values) {
            addCriterion("value_date not in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateBetween(Date value1, Date value2) {
            addCriterion("value_date between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotBetween(Date value1, Date value2) {
            addCriterion("value_date not between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNull() {
            addCriterion("expire_date is null");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNotNull() {
            addCriterion("expire_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpireDateEqualTo(Date value) {
            addCriterion("expire_date =", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotEqualTo(Date value) {
            addCriterion("expire_date <>", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThan(Date value) {
            addCriterion("expire_date >", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThanOrEqualTo(Date value) {
            addCriterion("expire_date >=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThan(Date value) {
            addCriterion("expire_date <", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThanOrEqualTo(Date value) {
            addCriterion("expire_date <=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIn(List<Date> values) {
            addCriterion("expire_date in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotIn(List<Date> values) {
            addCriterion("expire_date not in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateBetween(Date value1, Date value2) {
            addCriterion("expire_date between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotBetween(Date value1, Date value2) {
            addCriterion("expire_date not between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(String value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(String value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(String value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(String value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(String value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(String value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLike(String value) {
            addCriterion("period like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotLike(String value) {
            addCriterion("period not like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<String> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<String> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(String value1, String value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(String value1, String value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 28 10:12:52 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}