package com.hua.shi.rmd.domain.entity.category;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CategoryInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.id
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.sys_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String sysCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.sys_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String sysName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.big_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String bigCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.big_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String bigName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.small_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String smallCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.small_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String smallName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.bid_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String bidCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.bid_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private String bidName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_at
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private Integer createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_time
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.yield_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private BigDecimal yieldRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.risk_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private BigDecimal riskRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.id
     *
     * @return the value of t_category.id
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.id
     *
     * @param id the value for t_category.id
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.sys_code
     *
     * @return the value of t_category.sys_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.sys_code
     *
     * @param sysCode the value for t_category.sys_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.sys_name
     *
     * @return the value of t_category.sys_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.sys_name
     *
     * @param sysName the value for t_category.sys_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.big_code
     *
     * @return the value of t_category.big_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getBigCode() {
        return bigCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.big_code
     *
     * @param bigCode the value for t_category.big_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setBigCode(String bigCode) {
        this.bigCode = bigCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.big_name
     *
     * @return the value of t_category.big_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getBigName() {
        return bigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.big_name
     *
     * @param bigName the value for t_category.big_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setBigName(String bigName) {
        this.bigName = bigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.small_code
     *
     * @return the value of t_category.small_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getSmallCode() {
        return smallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.small_code
     *
     * @param smallCode the value for t_category.small_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setSmallCode(String smallCode) {
        this.smallCode = smallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.small_name
     *
     * @return the value of t_category.small_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getSmallName() {
        return smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.small_name
     *
     * @param smallName the value for t_category.small_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setSmallName(String smallName) {
        this.smallName = smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.bid_code
     *
     * @return the value of t_category.bid_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getBidCode() {
        return bidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.bid_code
     *
     * @param bidCode the value for t_category.bid_code
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setBidCode(String bidCode) {
        this.bidCode = bidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.bid_name
     *
     * @return the value of t_category.bid_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public String getBidName() {
        return bidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.bid_name
     *
     * @param bidName the value for t_category.bid_name
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setBidName(String bidName) {
        this.bidName = bidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_at
     *
     * @return the value of t_category.create_at
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_at
     *
     * @param createAt the value for t_category.create_at
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_time
     *
     * @return the value of t_category.create_time
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_time
     *
     * @param createTime the value for t_category.create_time
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.yield_ratio
     *
     * @return the value of t_category.yield_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public BigDecimal getYieldRatio() {
        return yieldRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.yield_ratio
     *
     * @param yieldRatio the value for t_category.yield_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setYieldRatio(BigDecimal yieldRatio) {
        this.yieldRatio = yieldRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.risk_ratio
     *
     * @return the value of t_category.risk_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public BigDecimal getRiskRatio() {
        return riskRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.risk_ratio
     *
     * @param riskRatio the value for t_category.risk_ratio
     *
     * @mbg.generated Sun Nov 29 10:35:56 CST 2020
     */
    public void setRiskRatio(BigDecimal riskRatio) {
        this.riskRatio = riskRatio;
    }
}