package com.hua.shi.rmd.mapper.group;

import com.hua.shi.rmd.domain.entity.group.GroupInfo;
import com.hua.shi.rmd.domain.entity.group.GroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    long countByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int deleteByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    List<GroupInfo> selectByExampleWithRowbounds(GroupInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    List<GroupInfo> selectByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    GroupInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int updateByExample(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    int updateByPrimaryKey(GroupInfo record);


    List<GroupInfo>  getPrdGroupTmpSMAll(@Param("groupId") String groupId);
}