package com.hua.shi.rmd.mapper.group;

import com.hua.shi.rmd.domain.entity.group.GroupBasic;
import com.hua.shi.rmd.domain.entity.group.GroupBasicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GroupBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    long countByExample(GroupBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int deleteByExample(GroupBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int insert(GroupBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int insertSelective(GroupBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    List<GroupBasic> selectByExampleWithRowbounds(GroupBasicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    List<GroupBasic> selectByExample(GroupBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    GroupBasic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") GroupBasic record, @Param("example") GroupBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int updateByExample(@Param("record") GroupBasic record, @Param("example") GroupBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int updateByPrimaryKeySelective(GroupBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    int updateByPrimaryKey(GroupBasic record);


    List<GroupBasic>  getPrdGroupTmpSMAll(@Param("groupId") String groupId);
}