package com.hua.shi.rmd.mapper.finance;

import com.hua.shi.rmd.domain.entity.finance.FinanceInfo;
import com.hua.shi.rmd.domain.entity.finance.FinanceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FinanceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    long countByExample(FinanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int deleteByExample(FinanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int insert(FinanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int insertSelective(FinanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    List<FinanceInfo> selectByExampleWithRowbounds(FinanceInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    List<FinanceInfo> selectByExample(FinanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    FinanceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") FinanceInfo record, @Param("example") FinanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int updateByExample(@Param("record") FinanceInfo record, @Param("example") FinanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int updateByPrimaryKeySelective(FinanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_info
     *
     * @mbg.generated Sat Nov 28 10:12:52 CST 2020
     */
    int updateByPrimaryKey(FinanceInfo record);
}