package com.hua.shi.rmd.domain.entity.group;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GroupInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public GroupInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNull() {
            addCriterion("group_code is null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNotNull() {
            addCriterion("group_code is not null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeEqualTo(String value) {
            addCriterion("group_code =", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotEqualTo(String value) {
            addCriterion("group_code <>", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThan(String value) {
            addCriterion("group_code >", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("group_code >=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThan(String value) {
            addCriterion("group_code <", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("group_code <=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLike(String value) {
            addCriterion("group_code like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotLike(String value) {
            addCriterion("group_code not like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIn(List<String> values) {
            addCriterion("group_code in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotIn(List<String> values) {
            addCriterion("group_code not in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeBetween(String value1, String value2) {
            addCriterion("group_code between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotBetween(String value1, String value2) {
            addCriterion("group_code not between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNull() {
            addCriterion("group_name is null");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNotNull() {
            addCriterion("group_name is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNameEqualTo(String value) {
            addCriterion("group_name =", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotEqualTo(String value) {
            addCriterion("group_name <>", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThan(String value) {
            addCriterion("group_name >", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("group_name >=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThan(String value) {
            addCriterion("group_name <", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThanOrEqualTo(String value) {
            addCriterion("group_name <=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLike(String value) {
            addCriterion("group_name like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotLike(String value) {
            addCriterion("group_name not like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameIn(List<String> values) {
            addCriterion("group_name in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotIn(List<String> values) {
            addCriterion("group_name not in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameBetween(String value1, String value2) {
            addCriterion("group_name between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotBetween(String value1, String value2) {
            addCriterion("group_name not between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNull() {
            addCriterion("risk_level is null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNotNull() {
            addCriterion("risk_level is not null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelEqualTo(Byte value) {
            addCriterion("risk_level =", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotEqualTo(Byte value) {
            addCriterion("risk_level <>", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThan(Byte value) {
            addCriterion("risk_level >", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("risk_level >=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThan(Byte value) {
            addCriterion("risk_level <", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThanOrEqualTo(Byte value) {
            addCriterion("risk_level <=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIn(List<Byte> values) {
            addCriterion("risk_level in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotIn(List<Byte> values) {
            addCriterion("risk_level not in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelBetween(Byte value1, Byte value2) {
            addCriterion("risk_level between", value1, value2, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("risk_level not between", value1, value2, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioIsNull() {
            addCriterion("drop_down_ratio is null");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioIsNotNull() {
            addCriterion("drop_down_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioEqualTo(BigDecimal value) {
            addCriterion("drop_down_ratio =", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioNotEqualTo(BigDecimal value) {
            addCriterion("drop_down_ratio <>", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioGreaterThan(BigDecimal value) {
            addCriterion("drop_down_ratio >", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("drop_down_ratio >=", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioLessThan(BigDecimal value) {
            addCriterion("drop_down_ratio <", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("drop_down_ratio <=", value, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioIn(List<BigDecimal> values) {
            addCriterion("drop_down_ratio in", values, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioNotIn(List<BigDecimal> values) {
            addCriterion("drop_down_ratio not in", values, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("drop_down_ratio between", value1, value2, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andDropDownRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("drop_down_ratio not between", value1, value2, "dropDownRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioIsNull() {
            addCriterion("yield_ratio is null");
            return (Criteria) this;
        }

        public Criteria andYieldRatioIsNotNull() {
            addCriterion("yield_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andYieldRatioEqualTo(BigDecimal value) {
            addCriterion("yield_ratio =", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioNotEqualTo(BigDecimal value) {
            addCriterion("yield_ratio <>", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioGreaterThan(BigDecimal value) {
            addCriterion("yield_ratio >", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("yield_ratio >=", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioLessThan(BigDecimal value) {
            addCriterion("yield_ratio <", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("yield_ratio <=", value, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioIn(List<BigDecimal> values) {
            addCriterion("yield_ratio in", values, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioNotIn(List<BigDecimal> values) {
            addCriterion("yield_ratio not in", values, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("yield_ratio between", value1, value2, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andYieldRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("yield_ratio not between", value1, value2, "yieldRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioIsNull() {
            addCriterion("risk_ratio is null");
            return (Criteria) this;
        }

        public Criteria andRiskRatioIsNotNull() {
            addCriterion("risk_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andRiskRatioEqualTo(BigDecimal value) {
            addCriterion("risk_ratio =", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioNotEqualTo(BigDecimal value) {
            addCriterion("risk_ratio <>", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioGreaterThan(BigDecimal value) {
            addCriterion("risk_ratio >", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("risk_ratio >=", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioLessThan(BigDecimal value) {
            addCriterion("risk_ratio <", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("risk_ratio <=", value, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioIn(List<BigDecimal> values) {
            addCriterion("risk_ratio in", values, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioNotIn(List<BigDecimal> values) {
            addCriterion("risk_ratio not in", values, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("risk_ratio between", value1, value2, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andRiskRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("risk_ratio not between", value1, value2, "riskRatio");
            return (Criteria) this;
        }

        public Criteria andInvestTermIsNull() {
            addCriterion("invest_term is null");
            return (Criteria) this;
        }

        public Criteria andInvestTermIsNotNull() {
            addCriterion("invest_term is not null");
            return (Criteria) this;
        }

        public Criteria andInvestTermEqualTo(String value) {
            addCriterion("invest_term =", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermNotEqualTo(String value) {
            addCriterion("invest_term <>", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermGreaterThan(String value) {
            addCriterion("invest_term >", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermGreaterThanOrEqualTo(String value) {
            addCriterion("invest_term >=", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermLessThan(String value) {
            addCriterion("invest_term <", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermLessThanOrEqualTo(String value) {
            addCriterion("invest_term <=", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermLike(String value) {
            addCriterion("invest_term like", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermNotLike(String value) {
            addCriterion("invest_term not like", value, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermIn(List<String> values) {
            addCriterion("invest_term in", values, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermNotIn(List<String> values) {
            addCriterion("invest_term not in", values, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermBetween(String value1, String value2) {
            addCriterion("invest_term between", value1, value2, "investTerm");
            return (Criteria) this;
        }

        public Criteria andInvestTermNotBetween(String value1, String value2) {
            addCriterion("invest_term not between", value1, value2, "investTerm");
            return (Criteria) this;
        }

        public Criteria andMinStartDateIsNull() {
            addCriterion("min_start_date is null");
            return (Criteria) this;
        }

        public Criteria andMinStartDateIsNotNull() {
            addCriterion("min_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andMinStartDateEqualTo(Date value) {
            addCriterion("min_start_date =", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateNotEqualTo(Date value) {
            addCriterion("min_start_date <>", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateGreaterThan(Date value) {
            addCriterion("min_start_date >", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("min_start_date >=", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateLessThan(Date value) {
            addCriterion("min_start_date <", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateLessThanOrEqualTo(Date value) {
            addCriterion("min_start_date <=", value, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateIn(List<Date> values) {
            addCriterion("min_start_date in", values, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateNotIn(List<Date> values) {
            addCriterion("min_start_date not in", values, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateBetween(Date value1, Date value2) {
            addCriterion("min_start_date between", value1, value2, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMinStartDateNotBetween(Date value1, Date value2) {
            addCriterion("min_start_date not between", value1, value2, "minStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateIsNull() {
            addCriterion("max_start_date is null");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateIsNotNull() {
            addCriterion("max_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateEqualTo(Date value) {
            addCriterion("max_start_date =", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateNotEqualTo(Date value) {
            addCriterion("max_start_date <>", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateGreaterThan(Date value) {
            addCriterion("max_start_date >", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("max_start_date >=", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateLessThan(Date value) {
            addCriterion("max_start_date <", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateLessThanOrEqualTo(Date value) {
            addCriterion("max_start_date <=", value, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateIn(List<Date> values) {
            addCriterion("max_start_date in", values, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateNotIn(List<Date> values) {
            addCriterion("max_start_date not in", values, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateBetween(Date value1, Date value2) {
            addCriterion("max_start_date between", value1, value2, "maxStartDate");
            return (Criteria) this;
        }

        public Criteria andMaxStartDateNotBetween(Date value1, Date value2) {
            addCriterion("max_start_date not between", value1, value2, "maxStartDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_group
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 29 13:40:06 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}