package com.hua.shi.rmd.domain.entity.group;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GroupBasic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.group_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.small_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String smallName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.small_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String smallCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.big_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String bigName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.big_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String bigCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.finance_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private String financeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.weight
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.create_id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_basic.create_time
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_basic
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.id
     *
     * @return the value of t_group_basic.id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.id
     *
     * @param id the value for t_group_basic.id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.group_code
     *
     * @return the value of t_group_basic.group_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.group_code
     *
     * @param groupCode the value for t_group_basic.group_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.small_name
     *
     * @return the value of t_group_basic.small_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getSmallName() {
        return smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.small_name
     *
     * @param smallName the value for t_group_basic.small_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setSmallName(String smallName) {
        this.smallName = smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.small_code
     *
     * @return the value of t_group_basic.small_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getSmallCode() {
        return smallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.small_code
     *
     * @param smallCode the value for t_group_basic.small_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setSmallCode(String smallCode) {
        this.smallCode = smallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.big_name
     *
     * @return the value of t_group_basic.big_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getBigName() {
        return bigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.big_name
     *
     * @param bigName the value for t_group_basic.big_name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setBigName(String bigName) {
        this.bigName = bigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.big_code
     *
     * @return the value of t_group_basic.big_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getBigCode() {
        return bigCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.big_code
     *
     * @param bigCode the value for t_group_basic.big_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setBigCode(String bigCode) {
        this.bigCode = bigCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.name
     *
     * @return the value of t_group_basic.name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.name
     *
     * @param name the value for t_group_basic.name
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.finance_code
     *
     * @return the value of t_group_basic.finance_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public String getFinanceCode() {
        return financeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.finance_code
     *
     * @param financeCode the value for t_group_basic.finance_code
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setFinanceCode(String financeCode) {
        this.financeCode = financeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.weight
     *
     * @return the value of t_group_basic.weight
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.weight
     *
     * @param weight the value for t_group_basic.weight
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.create_id
     *
     * @return the value of t_group_basic.create_id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.create_id
     *
     * @param createId the value for t_group_basic.create_id
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_basic.create_time
     *
     * @return the value of t_group_basic.create_time
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_basic.create_time
     *
     * @param createTime the value for t_group_basic.create_time
     *
     * @mbg.generated Sun May 30 16:04:07 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}