package com.hua.shi.rmd.domain.entity.group;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GroupInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.id
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.group_code
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.group_name
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.source
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.channel
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.risk_level
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private Byte riskLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.drop_down_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private BigDecimal dropDownRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.yield_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private BigDecimal yieldRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.risk_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private BigDecimal riskRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.invest_term
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private String investTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.min_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private Date minStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_finance_group.max_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private Date maxStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_finance_group
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.id
     *
     * @return the value of t_finance_group.id
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.id
     *
     * @param id the value for t_finance_group.id
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.group_code
     *
     * @return the value of t_finance_group.group_code
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.group_code
     *
     * @param groupCode the value for t_finance_group.group_code
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.group_name
     *
     * @return the value of t_finance_group.group_name
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.group_name
     *
     * @param groupName the value for t_finance_group.group_name
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.source
     *
     * @return the value of t_finance_group.source
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.source
     *
     * @param source the value for t_finance_group.source
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.channel
     *
     * @return the value of t_finance_group.channel
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.channel
     *
     * @param channel the value for t_finance_group.channel
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.risk_level
     *
     * @return the value of t_finance_group.risk_level
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Byte getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.risk_level
     *
     * @param riskLevel the value for t_finance_group.risk_level
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setRiskLevel(Byte riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.drop_down_ratio
     *
     * @return the value of t_finance_group.drop_down_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public BigDecimal getDropDownRatio() {
        return dropDownRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.drop_down_ratio
     *
     * @param dropDownRatio the value for t_finance_group.drop_down_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setDropDownRatio(BigDecimal dropDownRatio) {
        this.dropDownRatio = dropDownRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.yield_ratio
     *
     * @return the value of t_finance_group.yield_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public BigDecimal getYieldRatio() {
        return yieldRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.yield_ratio
     *
     * @param yieldRatio the value for t_finance_group.yield_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setYieldRatio(BigDecimal yieldRatio) {
        this.yieldRatio = yieldRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.risk_ratio
     *
     * @return the value of t_finance_group.risk_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public BigDecimal getRiskRatio() {
        return riskRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.risk_ratio
     *
     * @param riskRatio the value for t_finance_group.risk_ratio
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setRiskRatio(BigDecimal riskRatio) {
        this.riskRatio = riskRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.invest_term
     *
     * @return the value of t_finance_group.invest_term
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public String getInvestTerm() {
        return investTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.invest_term
     *
     * @param investTerm the value for t_finance_group.invest_term
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setInvestTerm(String investTerm) {
        this.investTerm = investTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.min_start_date
     *
     * @return the value of t_finance_group.min_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Date getMinStartDate() {
        return minStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.min_start_date
     *
     * @param minStartDate the value for t_finance_group.min_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setMinStartDate(Date minStartDate) {
        this.minStartDate = minStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_finance_group.max_start_date
     *
     * @return the value of t_finance_group.max_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public Date getMaxStartDate() {
        return maxStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_finance_group.max_start_date
     *
     * @param maxStartDate the value for t_finance_group.max_start_date
     *
     * @mbg.generated Sun Nov 29 13:40:06 CST 2020
     */
    public void setMaxStartDate(Date maxStartDate) {
        this.maxStartDate = maxStartDate;
    }
}