package com.hua.shi.rmd.domain.entity.role;

import java.io.Serializable;

public class RoleInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_name
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_remark
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private String roleRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.status
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_level
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private String roleLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_role
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.role_name
     *
     * @return the value of t_user_role.role_name
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.role_name
     *
     * @param roleName the value for t_user_role.role_name
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.role_remark
     *
     * @return the value of t_user_role.role_remark
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.role_remark
     *
     * @param roleRemark the value for t_user_role.role_remark
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.status
     *
     * @return the value of t_user_role.status
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.status
     *
     * @param status the value for t_user_role.status
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.role_level
     *
     * @return the value of t_user_role.role_level
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public String getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.role_level
     *
     * @param roleLevel the value for t_user_role.role_level
     *
     * @mbg.generated Wed Nov 25 23:13:47 CST 2020
     */
    public void setRoleLevel(String roleLevel) {
        this.roleLevel = roleLevel;
    }
}