package com.hua.shi.rmd.domain.entity.menu;

import java.io.Serializable;

public class MenuInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.menu_name
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.parent_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.menu_level
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private String menuLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.menu_url
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.menu_desc
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private String menuDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.menu_status
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private Byte menuStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_info.role_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu_info
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.id
     *
     * @return the value of t_menu_info.id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.id
     *
     * @param id the value for t_menu_info.id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.menu_name
     *
     * @return the value of t_menu_info.menu_name
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.menu_name
     *
     * @param menuName the value for t_menu_info.menu_name
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.parent_id
     *
     * @return the value of t_menu_info.parent_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.parent_id
     *
     * @param parentId the value for t_menu_info.parent_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.menu_level
     *
     * @return the value of t_menu_info.menu_level
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public String getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.menu_level
     *
     * @param menuLevel the value for t_menu_info.menu_level
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setMenuLevel(String menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.menu_url
     *
     * @return the value of t_menu_info.menu_url
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.menu_url
     *
     * @param menuUrl the value for t_menu_info.menu_url
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.menu_desc
     *
     * @return the value of t_menu_info.menu_desc
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.menu_desc
     *
     * @param menuDesc the value for t_menu_info.menu_desc
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.menu_status
     *
     * @return the value of t_menu_info.menu_status
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public Byte getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.menu_status
     *
     * @param menuStatus the value for t_menu_info.menu_status
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setMenuStatus(Byte menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_info.role_id
     *
     * @return the value of t_menu_info.role_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_info.role_id
     *
     * @param roleId the value for t_menu_info.role_id
     *
     * @mbg.generated Wed Nov 25 23:16:33 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}