# spring 配置
spring:
  application:
    name: rmd
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: ${driver_name}
    username: ${jdbc_username}
    password: ${jdbc_password}
    type: ${jdbc_type}
    url: ${jdbc_url}
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-agent-address: true

server:
  port: 8088
  servlet:
    context-path: /rmd

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hua.shi.rmd.domanin.entity


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

swagger:
  enable: ${swagger_enable}